version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: dockerfiles/rails/Dockerfile
    container_name: "todoct-app"
    ports:
      - "3008:3003"
    volumes:
      - "./:/app"
    environment:
      TODOCT_DATABASE_USER: root
      TODOCT_DATABASE_PASSWORD: root
      TODOCT_DATABASE_HOST: mysql
      EDITOR: vim
    tty: true
    stdin_open: true
    depends_on:
      - mysql

  mysql:
    build:
      context: dockerfiles/mysql
      dockerfile: Dockerfile
    container_name: "todoct-db"
    ports:
      - "3318:3306"
    volumes:
      - "./tmp/mysql/volumes/mysql:/var/lib/mysql"
      - "./tmp/mysql/volumes/initdb:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PORT_3306_TCP_ADDR: "localhost"
      MYSQL_PORT_3306_TCP_PORT: 3306
    tty: true
